### ISSUE TITLE
Wiki Documents

### ISSUE THREAD

**Issue by anastassia-b** [achynaliev/AppStarter#1]
Hey Atai,

Good work on the wiki for your full stack proposal. I've had the chance to review it and here is my feedback:

# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

### Comments:

- [x] Please review [markdown formatting](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet). Change `#AppStarter` to `# AppStarter` for formatting to take effect.

# MVP List

- [x] Should have 7 MVPs
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md)
- [x] Contains a description sentence of the app
- [x] At least one-two CRUD features
  - [x] Each feature states what CRUD operations are planned (creating, reading, editing, deleting)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted

### Comments:

- [x] Include bullet point descriptions, date, and estimated time for each MVP, [like this page](https://github.com/appacademy/bluebird/wiki/mvp-list).
- [x] Move the extra MVPs to a bonus section at the bottom of the page.

# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] index
    - [x] foreign key
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

### Comments:

- [x] Follow the formatting of (this example)[https://github.com/appacademy/bluebird/wiki/schema].
- [x] Add indexes to foreign keys.
- [x] You don't need to store a `total_funded` column in the `projects` table. This is a calculation that will be done in the `Project` model, as a custom method based on the rewards:

```ruby
class Project < ApplicationRecord
  def total_funded
    #calculate funding based on adding up self.rewards's pledge_amount
  end
end
```

(If you want to store the total_funded on the project, then you need to update the project in the database every time a new backing is made.)

- [x] `short_description` is type `text` while `full_description` is type `string`-- Did you mean to switch these? Please look into the difference between the two types and which one is appropriate.
- [x] You do not need a `category` column in the projects table, since there is a category table.
- [x] There DOES need to be a project_categories JOINS table, which stores the many-many relationship between projects and categories. It will store a `project_id` and `category_id`.
- [x] The Reading and Recommendation tables are not part of the MVPs, please delete them/move them to bonus at the bottom.

Nice added associations section!

**Comment by anastassia-b** [comment]
# Routes

- Contains the following sections:
  - [x] HTML
  - [x] API Endpoints(Backend)
  - [x] Frontend Routes
- [x] Routes accurately reflect MVPs and Component Hierarchy
- [x] Covers the frontend functionality of the site through routes that match to the wireframes
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes.
- [x] Correctly formatted
  - [x] Routes are displayed with `inline coding text` (backticks)

### Comments:

- [x] Do not need the `/#users/:id` frontend route. User profiles can be bonus, not part of the MVP list.
- [x] Add a frontend routes should look like this: `/#/explore`, with a slash after the hash.
- [x] Readings and Recommended are not part of the MVPs.
- [x] Fix backend routes for a user making a new project "backing". Would that be a POST to what route?
- [x] Do not need `/api/session GET` route.
- [x] Projects need a route to be edited (`PATCH`).
- [x] Missing `Category` MVP. What routes are needed?
- [x] Missing `Search` MVP. What routes are needed?

**Comment by achynaliev** [comment]
Hey Anastassia, so I added a new table 

project_categories

col_name | data_type | details
-- | -- | --
id | integer | not null, primary_key
project_id | integer | not null, foreign_key, indexed
category_id | integer | not null, foreign_key, indexed

do associations look right?

has_one category through project_categories 
has_many projects through project_categories

Thanks

**Comment by anastassia-b** [comment]
# Sample State

- [x] State shape is flat
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema (Ex: if you create a `img_url` key in the state, make sure your database also has a column that contains an `img_url`)
- [x] Correctly formatted
    - [x] Sample state is rendered with 3 back ticks before and after. This will display the state as a code block instead of a giant line of text/image.
- [x] Top level slices
  - [x] `entities`
  - [x] `session`
  - [x] `errors` (here or in `ui`)
  - [x] `ui` (if needed)

### Comments:

- [x] Readings and Recommendations are not part of the MVP list.
- [x] How will a project know which rewards to display on its page? A project needs to have a `rewardIds` to key into the rewards slice of state. This will be built with json on the backend through associations. This is similar to when we fetched a pokemon, we also got a pokemon's items with one request.
- [x] Like above, a project also needs to know its `categoryIds`.
* You may want to think about including additional information per project, such as a `backedByCurrentUser` boolean. This could help you change the display of the page if a user has backed the project already.

# Component Hierarchy with Wireframes

- [x] Each component, if necessary, has route, state, and other components it renders like this [example](https://github.com/appacademy/bluebird/wiki/component-hierarchy). Planning this really helps in the long run.
- [x] Necessary components are wrapped in a container. Some containers are missing.

Thank you for putting a lot of time into this. The User profile view is not part of the MVPs; it can be bonus. The project creation, listing, signup, and login pages look good! The homepage may look a little different given than what is proposed. We can meet to discuss how search will look in person.

**Comment by anastassia-b** [comment]
Hey @achynaliev -- yep, the `project_categories` table looks good to me! However, a project can belong to many categories, correct? This will allow us to filter projects by categories. Therefore:

a project: has_many categories, 
a category: has_many projects, 
a project_category: belongs_to a project, and belongs_to a category. 

If you only want a project to belong to one category, you can change the DB Schema to be a 1-many relationship, and project can just store its `category_id`. You don't need a joins table then. But its nice if a project can belong to multiple categories. :)

**Comment by achynaliev** [comment]
cool, thanks

**Comment by achynaliev** [comment]
@anastassia-b I think I am done with all issues here, please let me know if there is something else that I need to fix. Thanks!
