### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by achynaliev** [achynaliev/AppStarter#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by achynaliev** [comment]
@anastassia-b Hey Anastassia please take a look at user authentication when you got time. Here is link to heroku  https://apstarter.herokuapp.com . Thank you

**Comment by anastassia-b** [comment]
Works well! Please add error-handling to complete this MVP:
- [x] Errors render for Login
- [x] Errors render for Signup
- [x] Errors clear when toggling between forms or when correctly logging in

**Comment by achynaliev** [comment]
@anastassia-b I think I got it right. Please double check again on heroku. I will work on this forms some more when will be done with rest of the things.

**Comment by anastassia-b** [comment]
Awesome! I can log in and out and sign up. The demo user works as well. The errors all render and clear correctly, sweet! When we met, you added some more styles to center and move the login link. This MVP is complete.
