### ISSUE TITLE
PA Review: Project CRUD

### ISSUE THREAD

**Issue by achynaliev** [achynaliev/AppStarter#4]
- [x] Backend: DB, model, controller, views
 - [x] Redux Loop: ajax, actions, reducer
 - [x] Presentational Components
 - [x] Styling
 - [x] Smooth, bug-free navigation
 - [x] Adequate and appropriate seeds
 - [x] Project creation
 - [x] Project view page

**Comment by achynaliev** [comment]
hey @anastassia-b I think I am done with this, please take a look whenever you have time. Thank you!

**Comment by anastassia-b** [comment]
Awesome work! Beyond expectation. This MVP is complete.
