### ISSUE TITLE
PA Review: Backing projects & Rewards

### ISSUE THREAD

**Issue by anastassia-b** [achynaliev/AppStarter#6]
- [x] AppStarter users can back projects and get rewards (CREATE)
- [x] Users can cancel a backing (DELETE)
- [x] Project can have multiple reward types

- [x] Backend: controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by anastassia-b** [comment]
@achynaliev , This is great. 

- [x] The only thing is that the "total funded" should be updated when I back a project. Each project should have different total funding amounts, and it should be a calculation based on the backings of the project.
- [x] Therefore, if a project is below its funding amount, the green bar should be a percentage of its goal. It should change when I create/delete a backing. :) 
- [x] When I back/delete a backing, the Number of backers should change accordingly.

**Comment by anastassia-b** [comment]
Awesome work! This MVP is complete. :) I like your bonus features of the likes and recommended.

**Comment by achynaliev** [comment]
cooool, Thanks @anastassia-b !! you are the best!

**Comment by achynaliev** [comment]
green bar is done
